### ISSUE TITLE
Broken documentation generation since 5bf850e6

### ISSUE THREAD

**Issue by FlorianRhiem** [bastikr/sphinx-julia#16]
Hello, first off, thank you for Sphinx-Julia!

Starting with 5bf850e6d7e06bc8a47d610f2072120d11d1bd44 using Sphinx-Julia via `jl:autofile` for our documentation ([this file](https://github.com/jheinen/GR.jl/blob/master/src/GR.jl).) generates a lot of warnings, specifically hundreds of lines of `WARNING: Inline strong start-string without end-string.` and/or `WARNING: Inline substitution_reference start-string without end-string.`. The documentation does not seem to get recognized correctly and appears unformatted.

**Comment by bastikr** [comment]
Hi Florian,
I hope this was fixed by  #13 but I have to admit I didn't test it. Could you try it out? If it remains broken I will take a closer look.

**Comment by FlorianRhiem** [comment]
It works, thank you!
